//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Actions", typeof(Actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Control Panel.
        /// </summary>
        public static string AdministratorControlPanel {
            get {
                return ResourceManager.GetString("AdministratorControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To.
        /// </summary>
        public static string BackTo {
            get {
                return ResourceManager.GetString("BackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        public static string BackupDatabase {
            get {
                return ResourceManager.GetString("BackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Culture.
        /// </summary>
        public static string ChangeCulture {
            get {
                return ResourceManager.GetString("ChangeCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Manual.
        /// </summary>
        public static string CreateManual {
            get {
                return ResourceManager.GetString("CreateManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create of.
        /// </summary>
        public static string CreateOf {
            get {
                return ResourceManager.GetString("CreateOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Root.
        /// </summary>
        public static string CreateRoot {
            get {
                return ResourceManager.GetString("CreateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Responsible Users.
        /// </summary>
        public static string DefineResponsibleUsers {
            get {
                return ResourceManager.GetString("DefineResponsibleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete of.
        /// </summary>
        public static string DeleteOf {
            get {
                return ResourceManager.GetString("DeleteOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of.
        /// </summary>
        public static string DetailsOf {
            get {
                return ResourceManager.GetString("DetailsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details With Children.
        /// </summary>
        public static string DetailsWithChildren {
            get {
                return ResourceManager.GetString("DetailsWithChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayExamUsers.
        /// </summary>
        public static string DisplayExamUsers {
            get {
                return ResourceManager.GetString("DisplayExamUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display For Rss.
        /// </summary>
        public static string DisplayForRss {
            get {
                return ResourceManager.GetString("DisplayForRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display My Posts.
        /// </summary>
        public static string DisplayMyPosts {
            get {
                return ResourceManager.GetString("DisplayMyPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Online Users.
        /// </summary>
        public static string DisplayOnlineUsers {
            get {
                return ResourceManager.GetString("DisplayOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Page.
        /// </summary>
        public static string DisplayPage {
            get {
                return ResourceManager.GetString("DisplayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Photo.
        /// </summary>
        public static string DisplayPhoto {
            get {
                return ResourceManager.GetString("DisplayPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Photo With Details.
        /// </summary>
        public static string DisplayPhotoWithDetails {
            get {
                return ResourceManager.GetString("DisplayPhotoWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Profile.
        /// </summary>
        public static string DisplayProfile {
            get {
                return ResourceManager.GetString("DisplayProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Questions And Answers.
        /// </summary>
        public static string DisplayQuestionsAndAnswers {
            get {
                return ResourceManager.GetString("DisplayQuestionsAndAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Questions And Answers And Correct Answers.
        /// </summary>
        public static string DisplayQuestionsAndAnswersAndCorrectAnswers {
            get {
                return ResourceManager.GetString("DisplayQuestionsAndAnswersAndCorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Related Exams of Question.
        /// </summary>
        public static string DisplayRelatedExams {
            get {
                return ResourceManager.GetString("DisplayRelatedExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Resume.
        /// </summary>
        public static string DisplayResume {
            get {
                return ResourceManager.GetString("DisplayResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Sub Menu Items.
        /// </summary>
        public static string DisplaySubMenuItems {
            get {
                return ResourceManager.GetString("DisplaySubMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Sub Photo Album.
        /// </summary>
        public static string DisplaySubPhotoAlbum {
            get {
                return ResourceManager.GetString("DisplaySubPhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display User Avatar.
        /// </summary>
        public static string DisplayUserAvatar {
            get {
                return ResourceManager.GetString("DisplayUserAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display User Exam Details.
        /// </summary>
        public static string DisplayUserExamDetails {
            get {
                return ResourceManager.GetString("DisplayUserExamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display User Login Logs.
        /// </summary>
        public static string DisplayUserLoginLogs {
            get {
                return ResourceManager.GetString("DisplayUserLoginLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display User Profile.
        /// </summary>
        public static string DisplayUserProfile {
            get {
                return ResourceManager.GetString("DisplayUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Resume.
        /// </summary>
        public static string DownloadResume {
            get {
                return ResourceManager.GetString("DownloadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layout Content.
        /// </summary>
        public static string EditLayoutContent {
            get {
                return ResourceManager.GetString("EditLayoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Localized Page Content.
        /// </summary>
        public static string EditLocalizedPageContent {
            get {
                return ResourceManager.GetString("EditLocalizedPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit of.
        /// </summary>
        public static string EditOf {
            get {
                return ResourceManager.GetString("EditOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Error_AccessDenied {
            get {
                return ResourceManager.GetString("Error_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Not Found.
        /// </summary>
        public static string Error_HttpNotFound {
            get {
                return ResourceManager.GetString("Error_HttpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string Error_InvalidRequest {
            get {
                return ResourceManager.GetString("Error_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Offline.
        /// </summary>
        public static string Error_TemporaryOffline {
            get {
                return ResourceManager.GetString("Error_TemporaryOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected.
        /// </summary>
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Step of Update Profile.
        /// </summary>
        public static string FirstStepOfUpdateProfile {
            get {
                return ResourceManager.GetString("FirstStepOfUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixText.
        /// </summary>
        public static string FixText {
            get {
                return ResourceManager.GetString("FixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cities.
        /// </summary>
        public static string GetCities {
            get {
                return ResourceManager.GetString("GetCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        public static string GetData {
            get {
                return ResourceManager.GetString("GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Education Branches.
        /// </summary>
        public static string GetEducationBranches {
            get {
                return ResourceManager.GetString("GetEducationBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Education Places.
        /// </summary>
        public static string GetEducationPlaces {
            get {
                return ResourceManager.GetString("GetEducationPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Genders Count.
        /// </summary>
        public static string GetGendersCount {
            get {
                return ResourceManager.GetString("GetGendersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Online Users.
        /// </summary>
        public static string GetOnlineUsers {
            get {
                return ResourceManager.GetString("GetOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get People.
        /// </summary>
        public static string GetPeople {
            get {
                return ResourceManager.GetString("GetPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Posts.
        /// </summary>
        public static string GetPosts {
            get {
                return ResourceManager.GetString("GetPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Update Profile Progress Percent.
        /// </summary>
        public static string GetUpdateProfileProgressPercent {
            get {
                return ResourceManager.GetString("GetUpdateProfileProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Education Types Count.
        /// </summary>
        public static string GetUserEducationTypesCount {
            get {
                return ResourceManager.GetString("GetUserEducationTypesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Login Logs.
        /// </summary>
        public static string GetUserLoginLogs {
            get {
                return ResourceManager.GetString("GetUserLoginLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Posts.
        /// </summary>
        public static string GetUserPosts {
            get {
                return ResourceManager.GetString("GetUserPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Users.
        /// </summary>
        public static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User States.
        /// </summary>
        public static string GetUserStates {
            get {
                return ResourceManager.GetString("GetUserStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeOfParentMenuItem {
            get {
                return ResourceManager.GetString("HomeOfParentMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeOfParentPhotoAlbum {
            get {
                return ResourceManager.GetString("HomeOfParentPhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexOfRoot.
        /// </summary>
        public static string IndexOfRoot {
            get {
                return ResourceManager.GetString("IndexOfRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Users For Exam.
        /// </summary>
        public static string InviteUsersForExam {
            get {
                return ResourceManager.GetString("InviteUsersForExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of.
        /// </summary>
        public static string ListOf {
            get {
                return ResourceManager.GetString("ListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LocalizedTemplatesController_Edit {
            get {
                return ResourceManager.GetString("LocalizedTemplatesController_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string LocalizedTemplatesController_Index {
            get {
                return ResourceManager.GetString("LocalizedTemplatesController_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Folders And Files.
        /// </summary>
        public static string ManageFoldersAndFiles {
            get {
                return ResourceManager.GetString("ManageFoldersAndFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of.
        /// </summary>
        public static string ManageOf {
            get {
                return ResourceManager.GetString("ManageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Responsible Users.
        /// </summary>
        public static string ManageOfResponsibleUsers {
            get {
                return ResourceManager.GetString("ManageOfResponsibleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Users.
        /// </summary>
        public static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate.
        /// </summary>
        public static string Participate {
            get {
                return ResourceManager.GetString("Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Resume.
        /// </summary>
        public static string RegisterResume {
            get {
                return ResourceManager.GetString("RegisterResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Done.
        /// </summary>
        public static string RegistrationDone {
            get {
                return ResourceManager.GetString("RegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report 1.
        /// </summary>
        public static string Report1 {
            get {
                return ResourceManager.GetString("Report1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report 2.
        /// </summary>
        public static string Report2 {
            get {
                return ResourceManager.GetString("Report2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report 3.
        /// </summary>
        public static string Report3 {
            get {
                return ResourceManager.GetString("Report3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report 4.
        /// </summary>
        public static string Report4 {
            get {
                return ResourceManager.GetString("Report4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report 5.
        /// </summary>
        public static string Report5 {
            get {
                return ResourceManager.GetString("Report5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report 6.
        /// </summary>
        public static string Report6 {
            get {
                return ResourceManager.GetString("Report6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database.
        /// </summary>
        public static string RestoreDatabase {
            get {
                return ResourceManager.GetString("RestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actions.
        /// </summary>
        public static string SelectActions {
            get {
                return ResourceManager.GetString("SelectActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actions of.
        /// </summary>
        public static string SelectActionsOf {
            get {
                return ResourceManager.GetString("SelectActionsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Groups.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Groups of.
        /// </summary>
        public static string SelectGroupsOf {
            get {
                return ResourceManager.GetString("SelectGroupsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Labels.
        /// </summary>
        public static string SelectLabels {
            get {
                return ResourceManager.GetString("SelectLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Labels of.
        /// </summary>
        public static string SelectLabelsOf {
            get {
                return ResourceManager.GetString("SelectLabelsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pages.
        /// </summary>
        public static string SelectPages {
            get {
                return ResourceManager.GetString("SelectPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pages.
        /// </summary>
        public static string SelectPagesForGroup {
            get {
                return ResourceManager.GetString("SelectPagesForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pages For Layout.
        /// </summary>
        public static string SelectPagesForLayout {
            get {
                return ResourceManager.GetString("SelectPagesForLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pages of.
        /// </summary>
        public static string SelectPagesOf {
            get {
                return ResourceManager.GetString("SelectPagesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actions.
        /// </summary>
        public static string SelectProjectActionsForGroup {
            get {
                return ResourceManager.GetString("SelectProjectActionsForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actions.
        /// </summary>
        public static string SelectProjectActionsForLayout {
            get {
                return ResourceManager.GetString("SelectProjectActionsForLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Actions.
        /// </summary>
        public static string SelectProjectActionsForUser {
            get {
                return ResourceManager.GetString("SelectProjectActionsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Questions For Exam.
        /// </summary>
        public static string SelectQuestionsForExam {
            get {
                return ResourceManager.GetString("SelectQuestionsForExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Users.
        /// </summary>
        public static string SelectUsers {
            get {
                return ResourceManager.GetString("SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Users of.
        /// </summary>
        public static string SelectUsersOf {
            get {
                return ResourceManager.GetString("SelectUsersOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Again Cell Phone Verification Key.
        /// </summary>
        public static string SendAgainCellPhoneVerificationKey {
            get {
                return ResourceManager.GetString("SendAgainCellPhoneVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Again Email Address Verification Key.
        /// </summary>
        public static string SendAgainEmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("SendAgainEmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate Account.
        /// </summary>
        public static string TerminateAccount {
            get {
                return ResourceManager.GetString("TerminateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        public static string UploadAvatar {
            get {
                return ResourceManager.GetString("UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image For Course.
        /// </summary>
        public static string UploadImageForCourse {
            get {
                return ResourceManager.GetString("UploadImageForCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Resume.
        /// </summary>
        public static string UploadResume {
            get {
                return ResourceManager.GetString("UploadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control Panel.
        /// </summary>
        public static string UserControlPanel {
            get {
                return ResourceManager.GetString("UserControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dashboard.
        /// </summary>
        public static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Logs.
        /// </summary>
        public static string UserLoginLogs {
            get {
                return ResourceManager.GetString("UserLoginLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify User Cell Phone Number.
        /// </summary>
        public static string VerifyUserCellPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyUserCellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify User Email Address.
        /// </summary>
        public static string VerifyUserEmailAddress {
            get {
                return ResourceManager.GetString("VerifyUserEmailAddress", resourceCulture);
            }
        }
    }
}
