//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controllers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controllers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Controllers", typeof(Controllers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Access Types.
        /// </summary>
        public static string Administrator_AccessType {
            get {
                return ResourceManager.GetString("Administrator_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Address Categories.
        /// </summary>
        public static string Administrator_AddressCategory {
            get {
                return ResourceManager.GetString("Administrator_AddressCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Application Log.
        /// </summary>
        public static string Administrator_ApplicationLog {
            get {
                return ResourceManager.GetString("Administrator_ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Localized Application Settings.
        /// </summary>
        public static string Administrator_ApplicationSettings {
            get {
                return ResourceManager.GetString("Administrator_ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Cities.
        /// </summary>
        public static string Administrator_City {
            get {
                return ResourceManager.GetString("Administrator_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Cultures.
        /// </summary>
        public static string Administrator_Culture {
            get {
                return ResourceManager.GetString("Administrator_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Dashboard.
        /// </summary>
        public static string Administrator_Dashboard {
            get {
                return ResourceManager.GetString("Administrator_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        public static string Administrator_FileManager {
            get {
                return ResourceManager.GetString("Administrator_FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Files.
        /// </summary>
        public static string Administrator_Files {
            get {
                return ResourceManager.GetString("Administrator_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Genders.
        /// </summary>
        public static string Administrator_Gender {
            get {
                return ResourceManager.GetString("Administrator_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Application Settings.
        /// </summary>
        public static string Administrator_GlobalApplicationSettings {
            get {
                return ResourceManager.GetString("Administrator_GlobalApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Groups.
        /// </summary>
        public static string Administrator_Group {
            get {
                return ResourceManager.GetString("Administrator_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Referers.
        /// </summary>
        public static string Administrator_HttpReferer {
            get {
                return ResourceManager.GetString("Administrator_HttpReferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Localized Templates.
        /// </summary>
        public static string Administrator_LocalizedTemplates {
            get {
                return ResourceManager.GetString("Administrator_LocalizedTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of All of Mail Settings.
        /// </summary>
        public static string Administrator_MailSettings {
            get {
                return ResourceManager.GetString("Administrator_MailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer Services.
        /// </summary>
        public static string Administrator_Programmer {
            get {
                return ResourceManager.GetString("Administrator_Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Project Actions.
        /// </summary>
        public static string Administrator_ProjectAction {
            get {
                return ResourceManager.GetString("Administrator_ProjectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Project Areas.
        /// </summary>
        public static string Administrator_ProjectArea {
            get {
                return ResourceManager.GetString("Administrator_ProjectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Project Controllers.
        /// </summary>
        public static string Administrator_ProjectController {
            get {
                return ResourceManager.GetString("Administrator_ProjectController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Roles.
        /// </summary>
        public static string Administrator_Role {
            get {
                return ResourceManager.GetString("Administrator_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of States.
        /// </summary>
        public static string Administrator_State {
            get {
                return ResourceManager.GetString("Administrator_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Users.
        /// </summary>
        public static string Administrator_User {
            get {
                return ResourceManager.GetString("Administrator_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Users Login Logs.
        /// </summary>
        public static string Administrator_UserLoginLog {
            get {
                return ResourceManager.GetString("Administrator_UserLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Downloader.
        /// </summary>
        public static string Administrator_WebDownloader {
            get {
                return ResourceManager.GetString("Administrator_WebDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Complete.
        /// </summary>
        public static string AutoComplete {
            get {
                return ResourceManager.GetString("AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Layouts.
        /// </summary>
        public static string Cms_Layout {
            get {
                return ResourceManager.GetString("Cms_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Pages.
        /// </summary>
        public static string Cms_Page {
            get {
                return ResourceManager.GetString("Cms_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Posts.
        /// </summary>
        public static string Cms_Post {
            get {
                return ResourceManager.GetString("Cms_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Post Categories.
        /// </summary>
        public static string Cms_PostCategory {
            get {
                return ResourceManager.GetString("Cms_PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Tags.
        /// </summary>
        public static string Cms_Tag {
            get {
                return ResourceManager.GetString("Cms_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Errors.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Answers.
        /// </summary>
        public static string Lms_Answer {
            get {
                return ResourceManager.GetString("Lms_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Courses.
        /// </summary>
        public static string Lms_Course {
            get {
                return ResourceManager.GetString("Lms_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Course Sections.
        /// </summary>
        public static string Lms_CourseSection {
            get {
                return ResourceManager.GetString("Lms_CourseSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Course Section Analyzes.
        /// </summary>
        public static string Lms_CourseSectionAnalyze {
            get {
                return ResourceManager.GetString("Lms_CourseSectionAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Course Types.
        /// </summary>
        public static string Lms_CourseType {
            get {
                return ResourceManager.GetString("Lms_CourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Exams.
        /// </summary>
        public static string Lms_Exam {
            get {
                return ResourceManager.GetString("Lms_Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Questions of Exams.
        /// </summary>
        public static string Lms_ExamQuestion {
            get {
                return ResourceManager.GetString("Lms_ExamQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Images.
        /// </summary>
        public static string Lms_Image {
            get {
                return ResourceManager.GetString("Lms_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Questions.
        /// </summary>
        public static string Lms_Question {
            get {
                return ResourceManager.GetString("Lms_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Question Difficulties.
        /// </summary>
        public static string Lms_QuestionDifficulty {
            get {
                return ResourceManager.GetString("Lms_QuestionDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Exams of Users.
        /// </summary>
        public static string Lms_UserExam {
            get {
                return ResourceManager.GetString("Lms_UserExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Pages.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Posts.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage of Post Categories.
        /// </summary>
        public static string PostCategory {
            get {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss.
        /// </summary>
        public static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Logs.
        /// </summary>
        public static string UserLoginLog {
            get {
                return ResourceManager.GetString("UserLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Posts.
        /// </summary>
        public static string UserPost {
            get {
                return ResourceManager.GetString("UserPost", resourceCulture);
            }
        }
    }
}
