//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.ApplicationSettings", typeof(ApplicationSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Copyright Text.
        /// </summary>
        public static string ApplicationCopyrightText {
            get {
                return ResourceManager.GetString("ApplicationCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Copyright Url.
        /// </summary>
        public static string ApplicationCopyrightUrl {
            get {
                return ResourceManager.GetString("ApplicationCopyrightUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should User Attach File in Contact Us Page.
        /// </summary>
        public static string CanUserAttachFileInContactUsPage {
            get {
                return ResourceManager.GetString("CanUserAttachFileInContactUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can User Search The Others.
        /// </summary>
        public static string CanUserSearchTheOthers {
            get {
                return ResourceManager.GetString("CanUserSearchTheOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check National Code.
        /// </summary>
        public static string CheckNationalCode {
            get {
                return ResourceManager.GetString("CheckNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User Profile Level.
        /// </summary>
        public static string CurrentUserProfileLevel {
            get {
                return ResourceManager.GetString("CurrentUserProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force User To Update Profile After Login.
        /// </summary>
        public static string ForceUserToUpdateProfileAfterLogin {
            get {
                return ResourceManager.GetString("ForceUserToUpdateProfileAfterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Application in Demo Version.
        /// </summary>
        public static string IsApplicationInDemoVersion {
            get {
                return ResourceManager.GetString("IsApplicationInDemoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Captcha Image Enabled.
        /// </summary>
        public static string IsCaptchaImageEnabled {
            get {
                return ResourceManager.GetString("IsCaptchaImageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Cms Enabled.
        /// </summary>
        public static string IsCmsEnabled {
            get {
                return ResourceManager.GetString("IsCmsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ECommerce System Enabled.
        /// </summary>
        public static string IsECommerceSystemEnabled {
            get {
                return ResourceManager.GetString("IsECommerceSystemEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is EShop System Enabled.
        /// </summary>
        public static string IsEShopSystemEnabled {
            get {
                return ResourceManager.GetString("IsEShopSystemEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Registration Enabled.
        /// </summary>
        public static string IsRegistrationEnabled {
            get {
                return ResourceManager.GetString("IsRegistrationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SMS Service Enabled.
        /// </summary>
        public static string IsSmsServiceEnabled {
            get {
                return ResourceManager.GetString("IsSmsServiceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Ssl Enabled.
        /// </summary>
        public static string IsSslEnabled {
            get {
                return ResourceManager.GetString("IsSslEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is User Email Verification Required For Login.
        /// </summary>
        public static string IsUserEmailVerificationRequiredForLogin {
            get {
                return ResourceManager.GetString("IsUserEmailVerificationRequiredForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Image Url.
        /// </summary>
        public static string RssImageUrl {
            get {
                return ResourceManager.GetString("RssImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Item Count.
        /// </summary>
        public static string RssItemCount {
            get {
                return ResourceManager.GetString("RssItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO For Home Page.
        /// </summary>
        public static string SeoForHomePage {
            get {
                return ResourceManager.GetString("SeoForHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Time Zone Difference.
        /// </summary>
        public static string ServerTimeZoneDifference {
            get {
                return ResourceManager.GetString("ServerTimeZoneDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should User Be Activated After Registration.
        /// </summary>
        public static string ShouldUserBeActivatedAfterRegistration {
            get {
                return ResourceManager.GetString("ShouldUserBeActivatedAfterRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Timeout in Demo Version.
        /// </summary>
        public static string SleepTimeoutInDemoVersion {
            get {
                return ResourceManager.GetString("SleepTimeoutInDemoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Center Number.
        /// </summary>
        public static string SmsCenterNumber {
            get {
                return ResourceManager.GetString("SmsCenterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Center Password.
        /// </summary>
        public static string SmsCenterPassword {
            get {
                return ResourceManager.GetString("SmsCenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Center Username.
        /// </summary>
        public static string SmsCenterUsername {
            get {
                return ResourceManager.GetString("SmsCenterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total User Count.
        /// </summary>
        public static string TotalUserCount {
            get {
                return ResourceManager.GetString("TotalUserCount", resourceCulture);
            }
        }
    }
}
