//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserLoginLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserLoginLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.UserLoginLog", typeof(UserLoginLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Logs.
        /// </summary>
        public static string EntitiesName {
            get {
                return ResourceManager.GetString("EntitiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Logs of.
        /// </summary>
        public static string EntitiesNameOf {
            get {
                return ResourceManager.GetString("EntitiesNameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Log.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Log of.
        /// </summary>
        public static string EntityNameOf {
            get {
                return ResourceManager.GetString("EntityNameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hidden.
        /// </summary>
        public static string IsHidden {
            get {
                return ResourceManager.GetString("IsHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Date Time.
        /// </summary>
        public static string LoginDateTime {
            get {
                return ResourceManager.GetString("LoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Date Time.
        /// </summary>
        public static string LogoutDateTime {
            get {
                return ResourceManager.GetString("LogoutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Users.
        /// </summary>
        public static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Id.
        /// </summary>
        public static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }
    }
}
