//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Expire Date.
        /// </summary>
        public static string AccountExpireDate {
            get {
                return ResourceManager.GetString("AccountExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Terminate Date Time.
        /// </summary>
        public static string AccountTerminateDateTime {
            get {
                return ResourceManager.GetString("AccountTerminateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Description.
        /// </summary>
        public static string AdministratorDescription {
            get {
                return ResourceManager.GetString("AdministratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Number.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Card Number.
        /// </summary>
        public static string BankCardNumber {
            get {
                return ResourceManager.GetString("BankCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Shaba Number.
        /// </summary>
        public static string BankShabaNumber {
            get {
                return ResourceManager.GetString("BankShabaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number Verification Key.
        /// </summary>
        public static string CellPhoneNumberVerificationKey {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Not Verified Email Address Users.
        /// </summary>
        public static string DeleteNotVerifiedEmailAddressUsers {
            get {
                return ResourceManager.GetString("DeleteNotVerifiedEmailAddressUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Verification Key.
        /// </summary>
        public static string EmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string EntitiesName {
            get {
                return ResourceManager.GetString("EntitiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users of.
        /// </summary>
        public static string EntitiesNameOf {
            get {
                return ResourceManager.GetString("EntitiesNameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string EntityName {
            get {
                return ResourceManager.GetString("EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User of.
        /// </summary>
        public static string EntityNameOf {
            get {
                return ResourceManager.GetString("EntityNameOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is already exist! Please choose another one..
        /// </summary>
        public static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no any user with this email address!.
        /// </summary>
        public static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and/or Password is not correct! Please try again....
        /// </summary>
        public static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number is already exist! Please choose another one..
        /// </summary>
        public static string Error004 {
            get {
                return ResourceManager.GetString("Error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address was not verified! Please check your email box..
        /// </summary>
        public static string Error005 {
            get {
                return ResourceManager.GetString("Error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not login at this time! Please contact support..
        /// </summary>
        public static string Error006 {
            get {
                return ResourceManager.GetString("Error006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been already verified!.
        /// </summary>
        public static string Error007 {
            get {
                return ResourceManager.GetString("Error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify correct current password!.
        /// </summary>
        public static string Error008 {
            get {
                return ResourceManager.GetString("Error008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone number verification key is not valid!.
        /// </summary>
        public static string Error009 {
            get {
                return ResourceManager.GetString("Error009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code is not Valid!.
        /// </summary>
        public static string Error010 {
            get {
                return ResourceManager.GetString("Error010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Plan Date Time.
        /// </summary>
        public static string FinishPlanDateTime {
            get {
                return ResourceManager.GetString("FinishPlanDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Avatar.
        /// </summary>
        public static string HasAvatar {
            get {
                return ResourceManager.GetString("HasAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Resume.
        /// </summary>
        public static string HasResume {
            get {
                return ResourceManager.GetString("HasResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http Referer.
        /// </summary>
        public static string HttpReferer {
            get {
                return ResourceManager.GetString("HttpReferer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration done. We sent you an email for verification..
        /// </summary>
        public static string Information001 {
            get {
                return ResourceManager.GetString("Information001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send again the email address verification key..
        /// </summary>
        public static string Information002 {
            get {
                return ResourceManager.GetString("Information002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We generated a nice password and sent it to your email..
        /// </summary>
        public static string Information003 {
            get {
                return ResourceManager.GetString("Information003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password has been set for the user..
        /// </summary>
        public static string Information004 {
            get {
                return ResourceManager.GetString("Information004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password has been set..
        /// </summary>
        public static string Information005 {
            get {
                return ResourceManager.GetString("Information005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent again a SMS for your mobile verification..
        /// </summary>
        public static string Information006 {
            get {
                return ResourceManager.GetString("Information006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cell phone number is verified.
        /// </summary>
        public static string Information007 {
            get {
                return ResourceManager.GetString("Information007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Expirable.
        /// </summary>
        public static string IsAccountExpirable {
            get {
                return ResourceManager.GetString("IsAccountExpirable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Terminated.
        /// </summary>
        public static string IsAccountTerminated {
            get {
                return ResourceManager.GetString("IsAccountTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Address Public.
        /// </summary>
        public static string IsAddressPublic {
            get {
                return ResourceManager.GetString("IsAddressPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Avatar Public.
        /// </summary>
        public static string IsAvatarPublic {
            get {
                return ResourceManager.GetString("IsAvatarPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Birth Date Public.
        /// </summary>
        public static string IsBirthDatePublic {
            get {
                return ResourceManager.GetString("IsBirthDatePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Cell Phone Number Public.
        /// </summary>
        public static string IsCellPhoneNumberPublic {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone Number Verified.
        /// </summary>
        public static string IsCellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Contactable.
        /// </summary>
        public static string IsDirectContactable {
            get {
                return ResourceManager.GetString("IsDirectContactable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Email Address Public.
        /// </summary>
        public static string IsEmailAddressPublic {
            get {
                return ResourceManager.GetString("IsEmailAddressPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Verified.
        /// </summary>
        public static string IsEmailAddressVerified {
            get {
                return ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black List.
        /// </summary>
        public static string IsInBlackList {
            get {
                return ResourceManager.GetString("IsInBlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is Public.
        /// </summary>
        public static string IsProfilePublic {
            get {
                return ResourceManager.GetString("IsProfilePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login Date Time.
        /// </summary>
        public static string LastLoginDateTime {
            get {
                return ResourceManager.GetString("LastLoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Count.
        /// </summary>
        public static string LoginCount {
            get {
                return ResourceManager.GetString("LoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Code.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Level.
        /// </summary>
        public static string ProfileLevel {
            get {
                return ResourceManager.GetString("ProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date Time.
        /// </summary>
        public static string RegisterDateTime {
            get {
                return ResourceManager.GetString("RegisterDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register IP.
        /// </summary>
        public static string RegisterIP {
            get {
                return ResourceManager.GetString("RegisterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Date Time.
        /// </summary>
        public static string ResetPasswordDateTime {
            get {
                return ResourceManager.GetString("ResetPasswordDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Verification Key.
        /// </summary>
        public static string ResetPasswordVerificationKey {
            get {
                return ResourceManager.GetString("ResetPasswordVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Plan Date Time.
        /// </summary>
        public static string StartPlanDateTime {
            get {
                return ResourceManager.GetString("StartPlanDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Date Time.
        /// </summary>
        public static string UpdateProfileDateTime {
            get {
                return ResourceManager.GetString("UpdateProfileDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Bank Information.
        /// </summary>
        public static string UpdateUserBankInformation {
            get {
                return ResourceManager.GetString("UpdateUserBankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users List.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Email Address or Cell Phone Number.
        /// </summary>
        public static string VerifiedEmailAddressOrCellPhoneNumber {
            get {
                return ResourceManager.GetString("VerifiedEmailAddressOrCellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has full control and it does not need any permission!.
        /// </summary>
        public static string Warning001 {
            get {
                return ResourceManager.GetString("Warning001", resourceCulture);
            }
        }
    }
}
