//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MenuItems", typeof(MenuItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Control Panel.
        /// </summary>
        public static string AdministratorControlPanel {
            get {
                return ResourceManager.GetString("AdministratorControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.
        /// </summary>
        public static string Cms {
            get {
                return ResourceManager.GetString("Cms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Control Panel.
        /// </summary>
        public static string CmsControlPanel {
            get {
                return ResourceManager.GetString("CmsControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commerce System.
        /// </summary>
        public static string ECommerceSystem {
            get {
                return ResourceManager.GetString("ECommerceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EShop Control Panel.
        /// </summary>
        public static string EShopControlPanel {
            get {
                return ResourceManager.GetString("EShopControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EShop Control Panel For User.
        /// </summary>
        public static string EShopControlPanelForUser {
            get {
                return ResourceManager.GetString("EShopControlPanelForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Shop System.
        /// </summary>
        public static string EShopSystem {
            get {
                return ResourceManager.GetString("EShopSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer Control Panel.
        /// </summary>
        public static string ProgrammerControlPanel {
            get {
                return ResourceManager.GetString("ProgrammerControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email Control Panel.
        /// </summary>
        public static string SendingEmailControlPanel {
            get {
                return ResourceManager.GetString("SendingEmailControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control Panel.
        /// </summary>
        public static string UserControlPanel {
            get {
                return ResourceManager.GetString("UserControlPanel", resourceCulture);
            }
        }
    }
}
