//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.CMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.CMS.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Page.
        /// </summary>
        public static string DisplayPage {
            get {
                return ResourceManager.GetString("DisplayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Post.
        /// </summary>
        public static string DisplayPost {
            get {
                return ResourceManager.GetString("DisplayPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Post Categories.
        /// </summary>
        public static string DisplayPostCategories {
            get {
                return ResourceManager.GetString("DisplayPostCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Post Category.
        /// </summary>
        public static string DisplayPostCategory {
            get {
                return ResourceManager.GetString("DisplayPostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Posts.
        /// </summary>
        public static string DisplayPosts {
            get {
                return ResourceManager.GetString("DisplayPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Posts of Post Category.
        /// </summary>
        public static string DisplayPostsOfPostCategory {
            get {
                return ResourceManager.GetString("DisplayPostsOfPostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Actions.
        /// </summary>
        public static string GeneralActions {
            get {
                return ResourceManager.GetString("GeneralActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Random Data.
        /// </summary>
        public static string GenerateRandomData {
            get {
                return ResourceManager.GetString("GenerateRandomData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Posts.
        /// </summary>
        public static string GetPosts {
            get {
                return ResourceManager.GetString("GetPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Posts For Home Page.
        /// </summary>
        public static string GetPostsForHomePage {
            get {
                return ResourceManager.GetString("GetPostsForHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Posts of Post Category.
        /// </summary>
        public static string GetPostsOfPostCategory {
            get {
                return ResourceManager.GetString("GetPostsOfPostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Draft.
        /// </summary>
        public static string IsDraft {
            get {
                return ResourceManager.GetString("IsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Count.
        /// </summary>
        public static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Count.
        /// </summary>
        public static string PostCount {
            get {
                return ResourceManager.GetString("PostCount", resourceCulture);
            }
        }
    }
}
